/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package oilopt.gui;

import javax.swing.*;

/**
 *
 * @author r655
 */
public class MainWindow extends javax.swing.JFrame {

    
    DefaultListModel<Double> alphas = new DefaultListModel<Double>();
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        alphas.addElement(0.6);
        alphas.addElement(0.7);
        alphas.addElement(0.8);
        alphas.addElement(0.9);
        alphasList.setModel(alphas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alphaInputAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alphasList = new javax.swing.JList();
        alphaInput = new javax.swing.JTextField();
        generateBt = new javax.swing.JButton();
        removeAlpha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        alphaInputAdd.setText("Добавить");
        alphaInputAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alphaInputAddActionPerformed(evt);
            }
        });

        alphasList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        alphasList.setToolTipText("");
        jScrollPane1.setViewportView(alphasList);

        alphaInput.setToolTipText("Введите веростность &alpha;");

        generateBt.setText("Сгенерировать вывод");
        generateBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtActionPerformed(evt);
            }
        });

        removeAlpha.setText("Удалить");
        removeAlpha.setToolTipText("");
        removeAlpha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAlphaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(alphaInput)
                            .addGap(18, 18, 18)
                            .addComponent(alphaInputAdd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(removeAlpha)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(generateBt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alphaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alphaInputAdd)
                    .addComponent(removeAlpha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(generateBt)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alphaInputAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alphaInputAddActionPerformed
        String input = alphaInput.getText();
        String errorMessage = "Введите число в промежутке от 0.0 до 1.0";
        double value;
        try
        {
            value = Double.parseDouble(input);
            
            if(0.0 < value && value < 1.0)
            {
                if(!alphas.contains(value))
                    alphas.addElement(value);
            }
            else
            {
                // Show error
            }
        }
        catch(NumberFormatException e)
        {
            // Show error
        }
        finally
        {
            alphaInput.setText("");
        }
        
    }//GEN-LAST:event_alphaInputAddActionPerformed

    private void removeAlphaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAlphaActionPerformed
        
        int index = alphasList.getSelectedIndex();
        if(index >= 0)
            alphas.remove(index);
    }//GEN-LAST:event_removeAlphaActionPerformed

    private void generateBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtActionPerformed
        
        double[] alphasArray = new double[alphas.size()];
        for(int i = 0; i < alphasArray.length; ++i)
            alphasArray[i] = alphas.getElementAt(i);
        
        String[] files;
        try{
            files = oilopt.OilOpt.generateOutput(alphasArray);
            for(String file : files)
            {
                
                java.awt.Desktop.getDesktop().open(new java.io.File(file));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(jScrollPane1, e.getMessage());
        }
        
    }//GEN-LAST:event_generateBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void run(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alphaInput;
    private javax.swing.JButton alphaInputAdd;
    private javax.swing.JList alphasList;
    private javax.swing.JButton generateBt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeAlpha;
    // End of variables declaration//GEN-END:variables
}
