/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package oilopt.gui;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DataType;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;
import java.lang.reflect.Field;
import java.math.BigDecimal;
import javax.swing.*;
import java.util.*;
import oilopt.orm.GoodFromTool;
import oilopt.orm.NeedGoodForTool;

/**
 *
 * @author r655
 */
public class ORMGrid extends javax.swing.JFrame 
{
    static Map<String, String> readableNames  = new HashMap<String, String>()
    {{
        put("good", "Продукт");
        put("goodFromTool", "Полученный продукт");
        put("needGoodForTool", "Расходуемый продукт");
        put("needResourceForTool", "Расходуемый ресурс");
        put("resource", "Ресурс");
        put("tool", "Технология");
        put("id", "Ид");
        put("name", "Название");
        put("price", "Цена");
        put("goodId", "Идентификатор продукта");
        put("toolId", "Идентификатор технологии");
        put("resourceId", "Идентификатор ресурса");
        put("receiveNumber", "Полученное количество");
        put("requestNumber", "Требуемое количество");
        put("totalNumber", "Максимальное количество");
        put("deviation", "Дисперсия");
        put("abbreviation", "Аббревиатура");
        put("power", "Максимальная мощность");
    }};
    
    public ORMGrid(Class<?> ormClass, Object[] objs) throws Exception
    {
        
        if(!ormClass.isAnnotationPresent(DatabaseTable.class))
            throw new Exception("Need orm class");
        
        JFrame form = new JFrame();
        
        Field[] fields = ormClass.getDeclaredFields();
        final List<String> readableFieldsNames = new LinkedList<>();
        final List<Class> fieldsTypes = new LinkedList<>();
        final List<Field> originalFieldNames = new LinkedList<>();
        
        
        for(Field field: fields)
        {
            if (field.isAnnotationPresent(DatabaseField.class)) 
            {
                DatabaseField fieldParams = field.getAnnotation(DatabaseField.class);
                if(!fieldParams.foreign())
                {
                    originalFieldNames.add(field);
                    if(readableNames.containsKey(field.getName()))
                        readableFieldsNames.add(readableNames.get(field.getName()));
                    else
                        readableFieldsNames.add(field.getName());
                    
                    Class  cl = Integer.class;

                    switch(fieldParams.dataType())
                    {
                        case BOOLEAN:
                            cl = Boolean.class;
                        case BIG_DECIMAL:
                            cl = BigDecimal.class;
                        case UNKNOWN:
                            cl = Integer.class;
                        case INTEGER:
                            cl = Integer.class;
                        case DOUBLE:
                            cl = Double.class;
                        default:
                            cl = Integer.class;

                    }
                    fieldsTypes.add(cl);
                }
            }
        }
        
        
        Object[][] elems = new Object[objs.length][originalFieldNames.size()];
        int i = 0;
        for(Object obj: objs)
        {
            int j = 0;
            //elems[i] = new Object[originalFieldNames.size()];
            for(Field field: originalFieldNames)
            {
                
                elems[i][j] = obj.getClass().getMethod("get"+field.getName().substring(0, 1).toUpperCase() + field.getName().substring(1)).invoke(obj);
                ++j;
            }
            ++i;
        }
        
        initComponents();
        
        
        //ormtable = new JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            elems,
            readableFieldsNames.toArray()
        ) /*{
            final Class[] types = fieldsTypes.toArray();

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        }*/);
        
    }

    //JTable ormtable;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void start(final Class<?> ormClass, final Object[][] objs) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            final public void run() {
                try{
                    new ORMGrid(ormClass, objs).setVisible(true);
                }
                catch(Exception ex)
                {
                    ;
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
